

disabled_rules:
    - trailing_whitespace
    - colon
    - force_cast
    - identifier_name
    - cyclomatic_complexity
    - comment_spacing
    - unused_closure_parameter

line_length: 1000

type_body_length:
    warning: 450
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    
function_body_length:
    warning: 300
